package publisher

import (
	"fmt"
	"strings"

	"github.com/glorious-beard/locutus/internal/scaffold"
	"github.com/glorious-beard/locutus/internal/specio"
)

// Codex publisher. Format notes (subject to Phase 5 empirical
// verification; see the package-doc disclaimer in canonical.go):
//
//   - Subagents: .codex/agents/<file>.toml with TOML keys per the
//     plan (name, description, developer_instructions, model). Codex
//     doesn't support subdirectory namespacing inside .codex/agents/
//     as of design time, so the locutus-<id> filename prefix is the
//     namespace.
//   - Slash commands: .codex/commands/<file>.toml with similar TOML
//     shape; the body is the command's developer instructions.
//   - MCP servers: .codex/config.toml [mcp_servers."<name>"] tables.
//     Codex's MCP-server config lives at user-scope under
//     ~/.codex/config.toml; per-project config is supported via
//     .codex/config.toml. We write per-project so the Locutus MCP
//     attachment doesn't leak into every other Codex project on the
//     box.
//
// The TOML emission here is hand-rolled rather than using a TOML
// library because (a) the shapes are simple, (b) we control the
// output formatting, and (c) one fewer dependency. If the per-runtime
// shape grows, switching to a proper TOML library is a contained
// change.

func init() { registerRuntime(codexPublisher{}) }

type codexPublisher struct{}

func (codexPublisher) Name() string { return "codex" }

const codexMCPConfigPath = ".codex/config.toml"

func (codexPublisher) EnsureMCPConfig(fsys specio.FS) error {
	if err := fsys.MkdirAll(".codex", 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`# Locutus MCP server attachment for Codex.
# Generated by the Locutus publisher (DJ-135 phase 4); re-emitted
# on every locutus update --reset.

[mcp_servers.locutus]
command = %s
args = ["mcp"]
`, tomlString(locutusCommand()))
	return fsys.WriteFile(codexMCPConfigPath, []byte(content), 0o600)
}

func (codexPublisher) PublishAgent(agent CanonicalAgent, fsys specio.FS) error {
	dir := ".codex/agents"
	if err := fsys.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`name = "locutus-%s"
description = %s
developer_instructions = %s
`,
		agent.ID,
		tomlString(deriveDescription(agent)),
		tomlMultilineString(agent.Body),
	)
	path := fmt.Sprintf("%s/locutus-%s.toml", dir, agent.ID)
	return fsys.WriteFile(path, []byte(content), 0o644)
}

// EnsureHooks appends Locutus's TOML hook fragments to
// .codex/config.toml — one [[hooks]] table per activity that ships
// a hook (today: spec_refinement). The append is idempotent
// across re-runs because EnsureMCPConfig truncates the file first;
// EnsureHooks runs after slash commands but writes its delimited
// section that EnsureMCPConfig overwrites on the next reset.
//
// The fragment template carries the literal {{LOCUTUS_BIN}}
// placeholder that scaffold.ReadEmbeddedHook substitutes with the
// resolved locutus binary path (same path EnsureMCPConfig uses).
func (codexPublisher) EnsureHooks(activities []CanonicalActivity, fsys specio.FS) error {
	var sections []string
	for _, act := range activities {
		fragment, ok, err := scaffold.ReadEmbeddedHook("codex", act.Name, locutusCommand())
		if err != nil {
			return fmt.Errorf("read embedded hook for %s: %w", act.Name, err)
		}
		if !ok {
			continue
		}
		sections = append(sections, strings.TrimRight(string(fragment), "\n"))
	}
	if len(sections) == 0 {
		return nil
	}
	existing, err := fsys.ReadFile(codexMCPConfigPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", codexMCPConfigPath, err)
	}
	const marker = "\n# === locutus hooks (DJ-136) ===\n"
	// Strip any prior locutus-hooks section so re-runs converge to a
	// single block without duplicating tables.
	if idx := strings.Index(string(existing), marker); idx >= 0 {
		existing = existing[:idx]
	}
	updated := append(existing, []byte(marker)...)
	updated = append(updated, []byte(strings.Join(sections, "\n\n")+"\n")...)
	return fsys.WriteFile(codexMCPConfigPath, updated, 0o600)
}

func (codexPublisher) PublishActivity(act CanonicalActivity, fsys specio.FS) error {
	dir := ".codex/commands"
	if err := fsys.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`name = "locutus-%s"
description = %s
developer_instructions = %s
`,
		act.CLIVerb,
		tomlString(fmt.Sprintf("Locutus activity: %s", act.Name)),
		tomlMultilineString(act.PlanBody),
	)
	path := fmt.Sprintf("%s/locutus-%s.toml", dir, act.CLIVerb)
	return fsys.WriteFile(path, []byte(content), 0o644)
}

// tomlString emits a basic TOML string with backslash + quote
// escapes. Sufficient for the short titles / descriptions we emit;
// the multi-paragraph prompt bodies use tomlMultilineString.
func tomlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// tomlMultilineString emits a TOML literal multi-line string
// (triple-single-quote) that preserves the body verbatim. Literal
// strings don't process escapes, so a body containing backslashes or
// quotes stays byte-stable. The only forbidden sequence inside a
// literal multiline is the closing triple-single-quote — we don't
// expect that in agent prompts, but the function logs a warning by
// falling back to a fenced form if encountered.
func tomlMultilineString(body string) string {
	if strings.Contains(body, "'''") {
		// Defensive fallback: prompt contains the literal terminator.
		// Use a basic string with manual escapes instead. Loses
		// visual clarity but stays valid.
		escaped := strings.ReplaceAll(body, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		escaped = strings.ReplaceAll(escaped, "\n", `\n`)
		return `"` + escaped + `"`
	}
	return "'''\n" + body + "\n'''"
}
