// Package render provides data types and formatting for CLI output.
package render

// StatusData holds the gathered counts and flags for the status command.
type StatusData struct {
	GoalsPresent  bool
	FeatureCount  int
	DecisionCount int
	StrategyCount int
	BugCount      int
	EntityCount   int
	OrphanCount   int

	// InvalidatedApproaches lists Approach IDs that were marked
	// stale by a `refine --supersede` operation and not yet
	// regenerated by `locutus adopt`. Distinct from drifted
	// approaches: drifted means code drifted from a valid spec;
	// invalidated means spec drifted under valid code.
	InvalidatedApproaches []string
}
