package spec

import (
	"strings"
	"time"
)

// Approach is the synthesis leaf node — a self-contained implementation brief
// for a coding agent. It is always generated by Locutus (never hand-authored)
// and owned by exactly one parent Feature, Strategy, or Bug (ParentID).
//
// Stored as a pure .md file (YAML frontmatter + markdown body). No JSON sidecar.
type Approach struct {
	ID       string `yaml:"id"`
	Title    string `yaml:"title"`
	ParentID string `yaml:"parent_id"`

	// Body is the full synthesized markdown brief for the coding agent.
	// Natural-language prose including acceptance criteria narrative.
	// Machine-executable checks live in Assertions.
	// Updated during pre_flight when new assumed Decisions are recorded.
	Body string `yaml:"body,omitempty"`

	ArtifactPaths []string    `yaml:"artifact_paths,omitempty"`
	Decisions     []string    `yaml:"decisions,omitempty"`     // audit: decisions consulted during synthesis
	Skills        []string    `yaml:"skills,omitempty"`        // agent skill scripts
	Prerequisites []string    `yaml:"prerequisites,omitempty"` // CLI tools required before dispatch (e.g. ["buf", "jq"])
	Assertions    []Assertion `yaml:"assertions,omitempty"`    // machine-executable checks; reconciler runs these

	// InvalidatedByEventID points at the supersede history event that
	// invalidated this approach. Empty when the approach is valid.
	// Set by `refine --supersede` when the approach's parent or any
	// referenced decision is replaced. Adopt reads the referenced
	// event to understand why the approach is stale and what the
	// replacement target should be; the approach's other fields
	// (ArtifactPaths, Body, Assertions, Decisions) remain on disk
	// as the blast-radius input the next adopt run consumes.
	InvalidatedByEventID string `yaml:"invalidated_by_event_id,omitempty"`

	CreatedAt time.Time `yaml:"created_at"`
	UpdatedAt time.Time `yaml:"updated_at"`
}

// IsInvalidated reports whether this approach has been marked stale
// by a supersede operation. Whitespace-only event ids are treated as
// absent so a YAML quirk producing one accidentally doesn't flip the
// approach into an inconsistent state.
func (a Approach) IsInvalidated() bool {
	return strings.TrimSpace(a.InvalidatedByEventID) != ""
}
