package spec

import (
	"strings"
	"time"
)

// Approach is the synthesis leaf node — a self-contained implementation brief
// for a coding agent. It is always generated by Locutus (never hand-authored)
// and owned by exactly one parent Feature, Strategy, or Bug (ParentID).
//
// Stored as a pure .md file (YAML frontmatter + markdown body). No JSON sidecar.
type Approach struct {
	ID string `yaml:"id"`
	// Summary: see Decision.Summary. For approaches, summarises the
	// brief — what the coding agent is being asked to build.
	Summary  string `yaml:"summary,omitempty"`
	Title    string `yaml:"title"`
	ParentID string `yaml:"parent_id"`

	// Body is the full synthesized markdown brief for the coding agent.
	// Natural-language prose including acceptance criteria narrative.
	// Machine-executable checks live in Assertions.
	// Updated during pre_flight when new assumed Decisions are recorded.
	Body string `yaml:"body,omitempty"`

	ArtifactPaths []string    `yaml:"artifact_paths,omitempty"`
	Decisions     []string    `yaml:"decisions,omitempty"`     // audit: decisions consulted during synthesis
	Skills        []string    `yaml:"skills,omitempty"`        // agent skill scripts
	Prerequisites []string    `yaml:"prerequisites,omitempty"` // CLI tools required before dispatch (e.g. ["buf", "jq"])
	Assertions    []Assertion `yaml:"assertions,omitempty"`    // machine-executable checks; reconciler runs these

	// InvalidatedByEventID points at the history event that
	// invalidated this approach. Empty when the approach is valid.
	// Per [DJ-138](../../docs/decisions/dj-138-refine-with-bias-cascade.md),
	// the canonical write path is the spec_mark_approach_drifted MCP
	// tool, called by the spec_bias cascade playbook with the
	// originating spec_biased event id. Adopt reads the referenced
	// event to understand why the approach is stale and what the
	// replacement target should be; the approach's other fields
	// (ArtifactPaths, Body, Assertions, Decisions) remain on disk
	// as the blast-radius input the next adopt run consumes.
	InvalidatedByEventID string `yaml:"invalidated_by_event_id,omitempty"`

	// Advances lists goal-* ids this approach exists to advance
	// (DJ-139). Forward direction: the approach is justified because
	// it advances one or more in-scope goals (typically inherited
	// from its parent feature or strategy at synthesis time).
	// Optional informational citation — not a structural dependency.
	Advances []string `json:"advances,omitempty" yaml:"advances,omitempty"`
	// Respects lists agoal-* ids this approach was checked against
	// and admitted anyway (DJ-139). Boundary-navigation direction.
	// Optional informational citation — not a structural dependency.
	Respects []string `json:"respects,omitempty" yaml:"respects,omitempty"`

	// SourceFiles lists the source files this approach binds to,
	// relative to the project root. Populated by assimilate (DJ-148)
	// at synthesis time from the code that justified inferring the
	// parent feature/strategy; populated by adopt (DJ-149) on
	// approach synthesis for refine-added parents. Used by adopt's
	// drift detection to compute the current SourceHash for
	// comparison.
	SourceFiles []string `yaml:"source_files,omitempty"`

	// SourceHash is the sha256 hash over the concatenation of
	// (sorted-path-then-content) of each file in SourceFiles, in the
	// form sha256:<hex>. Computed by the agent and supplied to the
	// MCP tool — opaque to the daemon, which just stores it. DJ-149's
	// drift detection re-computes from current file content and
	// compares against this stored value to classify the approach.
	SourceHash string `yaml:"source_hash,omitempty"`

	// SourceHashSyncedAt records when the SourceHash was last
	// computed. Server-stamped on every propose/revise. Useful for
	// audit ("when did we last check this approach against code?")
	// and for surfacing stale-state warnings in adopt's classifier.
	SourceHashSyncedAt time.Time `yaml:"source_hash_synced_at,omitempty"`

	CreatedAt time.Time `yaml:"created_at"`
	UpdatedAt time.Time `yaml:"updated_at"`
}

// IsInvalidated reports whether this approach has been marked stale
// by a supersede operation. Whitespace-only event ids are treated as
// absent so a YAML quirk producing one accidentally doesn't flip the
// approach into an inconsistent state.
func (a Approach) IsInvalidated() bool {
	return strings.TrimSpace(a.InvalidatedByEventID) != ""
}
