package spec

import "time"

// Approach is the synthesis leaf node — a self-contained implementation brief
// for a coding agent. It is always generated by Locutus (never hand-authored)
// and owned by exactly one parent Feature, Strategy, or Bug (ParentID).
//
// Stored as a pure .md file (YAML frontmatter + markdown body). No JSON sidecar.
type Approach struct {
	ID       string `yaml:"id"`
	Title    string `yaml:"title"`
	ParentID string `yaml:"parent_id"`

	// Body is the full synthesized markdown brief for the coding agent.
	// Natural-language prose including acceptance criteria narrative.
	// Machine-executable checks live in Assertions.
	// Updated during pre_flight when new assumed Decisions are recorded.
	Body string `yaml:"body,omitempty"`

	ArtifactPaths []string    `yaml:"artifact_paths,omitempty"`
	Decisions     []string    `yaml:"decisions,omitempty"`     // audit: decisions consulted during synthesis
	Skills        []string    `yaml:"skills,omitempty"`        // agent skill scripts
	Prerequisites []string    `yaml:"prerequisites,omitempty"` // CLI tools required before dispatch (e.g. ["buf", "jq"])
	Assertions    []Assertion `yaml:"assertions,omitempty"`    // machine-executable checks; reconciler runs these

	CreatedAt time.Time `yaml:"created_at"`
	UpdatedAt time.Time `yaml:"updated_at"`
}
